language: node_js
os: osx
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: guhmOJmKzcFQ9qOIbedsCGZqC94u7SjT3Y8gTt3JLOFF12oq76xNuOu/4OZ+CfCrH+auFVRXZitrvmqvJzzUb+KXKc/8J9xVcEU3Mc/197oI19nT55OKW3N+Jo4RaZhPfoXXJv5s343oj4fdcs6BIHnqpYv2EBOuByILB673JR5PLWceM5lylmpBcB5aGTxSXzt9YCGC6fYLv3kY1ZNpwSn2v6uUbKJK4LatO3tciXoeDcE4OYIbBGORGz536PVYmd1x/fAB6Ay0Vwvpaz+Zh87OS97vmZacTLfu6sc4XlPoJmtZ6EQmFz5buJq0C+lgPLg26OcByR+ZE7h1FpeSHsSZVfaLZEn4xscTuPULf3Imn/+8/WmTXbeAOX425yLl3ROtgDruqdEh/46tSgu2I596Zc+Gnwvx6CnoV16bIG5clVeQhUlGWd9OuvwRiZIDr85Rpj4qg417223UkvfICvdqbIQ5LDutB1kD171Hbf4jf0Mgvdrl10uLjsdSFJ0qe6g9cQ4xkaEvsHBxCXD2w9eLW3rFAKbOh83NrWb7D5kCdWNkDRN/oMkYgDqY425W+3oVO9NzyrklFudZUFRh5Rczx/YUfr53MIUDi4AUDKxgaWQ9fk30J+QF4W4vvej6dq3KKBdRy37+9o907c0FhB6kJxlN2Nk67Vae1bVrxPg=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/is-key-down
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: iYN2e/gHbruZYePCLKbsHT30qgikRI+fyrr/SYEiZ0tqw1z2LCSIRJGGPzWNWdMAKy4ES5546ou1TAqsCKoDxzzljBc23+a7zoIGBpsaRH8QxMaN2l1pDvU+tX8zpeg73Y27AhLzcMrZZVO0cHLDHpJmWr7AaNJLhLKnOjR4ONxIS25PZfIOKGH/t4sMwAcyNCLkysMOCspMHKwX9q5J8WXwYD7A0xpcbvAISnvbIPCBiHFHf8IxvCaYgYtFYnnq1hNtmH0Kxm85yoGvC0nRmU4J8RNHWSV4qdzubSvOfZITtpzI/Rv38mJ4552is6eat9QdZJEGg+UR/3K0cgmhVvdfRtmO3sk0CF/SQTMLqxCL2sfgSIaRX0gzHIYB+QeKnzI9AlPQoCuIVJSVoaNhyVI0yzB/cN3jnGTagw91/HgMI5CXu72TyuzYk0p86txz47W9ddXY8gQR4dmcZm7zwE+GdTE9373LmjA/20LfFfsEykNvuBAgbaQxLhe9yoMIfZQFRU8kABOx6E3eQX5UrSWrxAfL3zKGYHyYM2/UBDCRT2CyDNHVvlN52wgkQuGRshIHl/HW29Qv1J5NnscgzgUSKPlf0vzkA0JiiKuCgRte1Ge8SYKGtR/EV/zPXIEl5c/Z2spBH+6B7w/qrs6WsOYVUCKCVOkmGcd3fKI5xcQ=
    on:
      branch: master
      tags: true
      repo: flekschas/is-key-down
